# Generated by Django 3.2.17 on 2023-02-16 11:36

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('modified_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=False, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('current_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('current_login_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('login_count', models.IntegerField(blank=True, default=0, null=True)),
                ('dict_status', models.TextField(default='on')),
                ('login_from', models.TextField()),
                ('conf_code', models.TextField(blank=True, null=True)),
                ('temp_password', models.TextField(blank=True, null=True)),
                ('reset_password_code', models.TextField(blank=True, null=True)),
                ('subscription_status', models.CharField(default='free_mode', max_length=25)),
                ('cus_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user_status', models.TextField(default='ENABLED')),
            ],
            options={
                'verbose_name': 'Auth User',
                'db_table': 'auth_user',
                'ordering': ['id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_role',
            },
        ),
    ]
