# Generated by Django 3.2.17 on 2023-02-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcxAPIx', '0002_auto_20230217_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='gcxAPIx.Role'),
        ),
    ]
